# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: All about Narciso learning
email: narciso.benigno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I will put here all about I am learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://narcisobenigno.github.io"
twitter_username: narcisobenigno
github_username:  narcisobenigno

# Build settings
markdown: kramdown
